const express  = require('express');
const multer   = require('multer');
const path     = require('path');
const fs       = require('fs');
const { v4: uuidv4 } = require('uuid');
const bcrypt   = require('bcryptjs');
const jwt      = require('jsonwebtoken');

const app = express();
const JWT_SECRET = process.env.JWT_SECRET || 'growthmarket-secret-2024';

// Persistent data dir (Render disk or local)
const DATA_DIR    = process.env.DATA_DIR || path.join(__dirname, 'data');
const UPLOADS_DIR = process.env.UPLOADS_DIR || path.join(__dirname, 'uploads');
[DATA_DIR, UPLOADS_DIR, path.join(UPLOADS_DIR,'images'), path.join(UPLOADS_DIR,'videos')].forEach(d => fs.mkdirSync(d, { recursive: true }));

app.use(express.static(path.join(__dirname, 'public')));
app.use(express.json());
app.use('/uploads', express.static(UPLOADS_DIR));

const LISTINGS_FILE   = path.join(DATA_DIR, 'listings.json');
const USERS_FILE      = path.join(DATA_DIR, 'users.json');
const MESSAGES_FILE   = path.join(DATA_DIR, 'messages.json');
const REVIEWS_FILE    = path.join(DATA_DIR, 'reviews.json');
const INVITES_FILE    = path.join(DATA_DIR, 'invites.json');
const FOLLOWS_FILE    = path.join(DATA_DIR, 'follows.json');
const BROADCASTS_FILE = path.join(DATA_DIR, 'broadcasts.json');
const STAMPS_FILE     = path.join(DATA_DIR, 'stamps.json');

function readJSON(file)        { try { return JSON.parse(fs.readFileSync(file,'utf8')); } catch { return []; } }
function writeJSON(file, data) { fs.writeFileSync(file, JSON.stringify(data, null, 2)); }

const PLANS = {
  free:   { name:'Free',          price:0,     features:['listing','gallery','analytics','featured_badge','seo_profile','priority_search'] },
  pro:    { name:'Business Pro',  price:9.99,  features:['listing','gallery','analytics','featured_badge','seo_profile','priority_search','invite_customers','community_feed','broadcasts','loyalty_stamps','custom_slug'] },
  growth: { name:'Growth Suite',  price:19.99, features:['listing','gallery','analytics','featured_badge','seo_profile','priority_search','invite_customers','community_feed','broadcasts','loyalty_stamps','custom_slug','competitor_analytics','lead_export','verified_badge','sponsored_listing','custom_cta'] }
};
function userHasFeature(user, feature) { return (PLANS[user?.plan||'free']?.features||PLANS.free.features).includes(feature); }

const storage = multer.diskStorage({
  destination:(req,file,cb)=>{ const isVid=file.mimetype.startsWith('video/'); const d=path.join(UPLOADS_DIR,isVid?'videos':'images'); fs.mkdirSync(d,{recursive:true}); cb(null,d); },
  filename:(req,file,cb)=>cb(null,uuidv4()+path.extname(file.originalname))
});
const upload = multer({ storage, fileFilter:(req,file,cb)=>cb(null,['image/jpeg','image/png','image/gif','image/webp','video/mp4','video/quicktime','video/webm'].includes(file.mimetype)), limits:{fileSize:50*1024*1024} });

function authMiddleware(req,res,next){ const t=(req.headers['authorization']||'').replace('Bearer ',''); if(!t) return res.status(401).json({error:'Unauthorised'}); try{ req.user=jwt.verify(t,JWT_SECRET); next(); }catch{ res.status(401).json({error:'Invalid token'}); } }
function optionalAuth(req,res,next){ const t=(req.headers['authorization']||'').replace('Bearer ',''); if(t){try{req.user=jwt.verify(t,JWT_SECRET);}catch{}} next(); }

// AUTH
app.post('/api/auth/register', async (req,res)=>{ try{ const {name,email,password,phone,country,businessName}=req.body; if(!name||!email||!password) return res.status(400).json({error:'name, email and password are required.'}); const users=readJSON(USERS_FILE); if(users.find(u=>u.email.toLowerCase()===email.toLowerCase())) return res.status(400).json({error:'Email already registered.'}); const hashed=await bcrypt.hash(password,10); const user={id:uuidv4(),createdAt:new Date().toISOString(),name:name.trim(),email:email.toLowerCase().trim(),password:hashed,phone:phone||null,country:country||null,businessName:businessName||null,avatar:null,verified:false,listingCount:0,plan:'free',planActivatedAt:null,planExpiresAt:null}; users.push(user); writeJSON(USERS_FILE,users); const token=jwt.sign({id:user.id,email:user.email,name:user.name},JWT_SECRET,{expiresIn:'30d'}); const {password:_,...safe}=user; res.json({success:true,token,user:safe}); }catch(err){console.error(err);res.status(500).json({error:'Server error.'});} });
app.post('/api/auth/login', async (req,res)=>{ try{ const {email,password}=req.body; if(!email||!password) return res.status(400).json({error:'Email and password required.'}); const users=readJSON(USERS_FILE); const user=users.find(u=>u.email.toLowerCase()===email.toLowerCase()); if(!user) return res.status(400).json({error:'Invalid email or password.'}); const match=await bcrypt.compare(password,user.password); if(!match) return res.status(400).json({error:'Invalid email or password.'}); const token=jwt.sign({id:user.id,email:user.email,name:user.name},JWT_SECRET,{expiresIn:'30d'}); const {password:_,...safe}=user; res.json({success:true,token,user:safe}); }catch(err){console.error(err);res.status(500).json({error:'Server error.'});} });
app.get('/api/auth/me', authMiddleware, (req,res)=>{ const users=readJSON(USERS_FILE); const user=users.find(u=>u.id===req.user.id); if(!user) return res.status(404).json({error:'User not found'}); const {password:_,...safe}=user; res.json(safe); });
app.put('/api/auth/profile', authMiddleware, upload.single('avatar'), (req,res)=>{ const users=readJSON(USERS_FILE); const idx=users.findIndex(u=>u.id===req.user.id); if(idx===-1) return res.status(404).json({error:'User not found'}); const {name,phone,country,businessName,bio}=req.body; if(name) users[idx].name=name.trim(); if(phone) users[idx].phone=phone; if(country) users[idx].country=country; if(businessName) users[idx].businessName=businessName; if(bio) users[idx].bio=bio; if(req.file) users[idx].avatar=`/uploads/images/${req.file.filename}`; writeJSON(USERS_FILE,users); const {password:_,...safe}=users[idx]; res.json({success:true,user:safe}); });

// PLANS
app.get('/api/plans', (req,res)=>res.json(PLANS));
app.post('/api/auth/upgrade', authMiddleware, (req,res)=>{ const {plan}=req.body; if(!PLANS[plan]) return res.status(400).json({error:'Invalid plan.'}); const users=readJSON(USERS_FILE); const idx=users.findIndex(u=>u.id===req.user.id); if(idx===-1) return res.status(404).json({error:'User not found'}); const now=new Date(); const expires=new Date(now); expires.setMonth(expires.getMonth()+1); users[idx].plan=plan; users[idx].planActivatedAt=now.toISOString(); users[idx].planExpiresAt=expires.toISOString(); writeJSON(USERS_FILE,users); const {password:_,...safe}=users[idx]; res.json({success:true,user:safe}); });

// LISTINGS
app.post('/api/listings', optionalAuth, upload.fields([{name:'images',maxCount:8},{name:'videos',maxCount:2}]), (req,res)=>{ try{ const {businessName,category,description,tagline,price,currency,priceType,whatsapp,phone,email,website,location,country,city,instagram,tiktok,facebook,twitter,youtube,contactName,contactRole,tags,openHours,established,employees,customSlug,customCta,ctaLabel}=req.body; if(!businessName||!description||!category) return res.status(400).json({error:'businessName, category and description are required.'}); const images=(req.files?.images||[]).map(f=>`/uploads/images/${f.filename}`); const videos=(req.files?.videos||[]).map(f=>`/uploads/videos/${f.filename}`); let slug=null; if(customSlug&&req.user){const owner=readJSON(USERS_FILE).find(u=>u.id===req.user.id);if(userHasFeature(owner,'custom_slug')){const existing=readJSON(LISTINGS_FILE).find(l=>l.slug===customSlug.toLowerCase().replace(/[^a-z0-9-]/g,''));if(!existing)slug=customSlug.toLowerCase().replace(/[^a-z0-9-]/g,'');}} let ctaConfig=null; if(customCta&&req.user){const owner=readJSON(USERS_FILE).find(u=>u.id===req.user.id);if(userHasFeature(owner,'custom_cta'))ctaConfig={url:customCta,label:ctaLabel||'Contact Now'};} const listing={id:uuidv4(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),status:'active',featured:false,sponsored:false,slug,ownerId:req.user?.id||null,ownerName:req.user?.name||contactName||null,businessName:businessName.trim(),tagline:tagline?.trim()||null,category,description:description.trim(),price:price||null,currency:currency||'USD',priceType:priceType||null,contact:{name:contactName||null,role:contactRole||null,whatsapp:whatsapp||null,phone:phone||null,email:email||null,website:website||null},location:location||null,country:country||null,city:city||null,social:{instagram:instagram||null,tiktok:tiktok||null,facebook:facebook||null,twitter:twitter||null,youtube:youtube||null},openHours:openHours||null,established:established||null,employees:employees||null,tags:tags?tags.split(',').map(t=>t.trim()).filter(Boolean):[],images,videos,views:0,leads:0,saves:0,reviewCount:0,rating:0,ctaConfig,analyticsHistory:[]}; const listings=readJSON(LISTINGS_FILE); listings.unshift(listing); writeJSON(LISTINGS_FILE,listings); if(req.user){const users=readJSON(USERS_FILE);const idx=users.findIndex(u=>u.id===req.user.id);if(idx!==-1){users[idx].listingCount=(users[idx].listingCount||0)+1;writeJSON(USERS_FILE,users);}} res.json({success:true,listing}); }catch(err){console.error(err);res.status(500).json({error:'Server error.'});} });

app.get('/api/listings', (req,res)=>{ const {category,country,city,search,featured,sponsored,ownerId,limit=20,offset=0,sort='newest'}=req.query; let listings=readJSON(LISTINGS_FILE).filter(l=>l.status==='active'); if(category&&category!=='all') listings=listings.filter(l=>l.category===category); if(country) listings=listings.filter(l=>l.country?.toLowerCase().includes(country.toLowerCase())); if(city) listings=listings.filter(l=>l.city?.toLowerCase().includes(city.toLowerCase())); if(featured==='true') listings=listings.filter(l=>l.featured); if(sponsored==='true') listings=listings.filter(l=>l.sponsored); if(ownerId) listings=listings.filter(l=>l.ownerId===ownerId); if(search){const q=search.toLowerCase();listings=listings.filter(l=>l.businessName.toLowerCase().includes(q)||l.description.toLowerCase().includes(q)||l.tagline?.toLowerCase().includes(q)||(l.tags||[]).some(t=>t.toLowerCase().includes(q))||l.city?.toLowerCase().includes(q)||l.country?.toLowerCase().includes(q));} const sp=listings.filter(l=>l.sponsored); const reg=listings.filter(l=>!l.sponsored); if(sort==='popular') reg.sort((a,b)=>(b.views||0)-(a.views||0)); else if(sort==='rating') reg.sort((a,b)=>(b.rating||0)-(a.rating||0)); else reg.sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)); const merged=[...sp,...reg]; res.json({total:merged.length,listings:merged.slice(Number(offset),Number(offset)+Number(limit))}); });

app.get('/api/listings/:id', (req,res)=>{ const listings=readJSON(LISTINGS_FILE); const listing=listings.find(l=>l.id===req.params.id||l.slug===req.params.id); if(!listing) return res.status(404).json({error:'Not found'}); listing.views=(listing.views||0)+1; const today=new Date().toISOString().slice(0,10); if(!listing.analyticsHistory) listing.analyticsHistory=[]; const te=listing.analyticsHistory.find(e=>e.date===today); if(te) te.views=(te.views||0)+1; else listing.analyticsHistory.push({date:today,views:1,leads:0}); if(listing.analyticsHistory.length>90) listing.analyticsHistory=listing.analyticsHistory.slice(-90); writeJSON(LISTINGS_FILE,listings.map(l=>l.id===listing.id?listing:l)); if(listing.ownerId){const users=readJSON(USERS_FILE);const owner=users.find(u=>u.id===listing.ownerId);if(owner){const {password:_,...safe}=owner;listing.owner=safe;listing.ownerPlan=safe.plan||'free';}} res.json(listing); });

app.put('/api/listings/:id', authMiddleware, upload.fields([{name:'images',maxCount:8},{name:'videos',maxCount:2}]), (req,res)=>{ const listings=readJSON(LISTINGS_FILE); const idx=listings.findIndex(l=>l.id===req.params.id); if(idx===-1) return res.status(404).json({error:'Not found'}); if(listings[idx].ownerId!==req.user.id) return res.status(403).json({error:'Forbidden'}); ['businessName','tagline','category','description','price','currency','priceType','location','country','city','contactName','contactRole','openHours','established','employees'].forEach(f=>{if(req.body[f]!==undefined) listings[idx][f]=req.body[f];}); ['whatsapp','phone','email','website'].forEach(f=>{if(req.body[f]!==undefined) listings[idx].contact[f]=req.body[f];}); ['instagram','tiktok','facebook','twitter','youtube'].forEach(f=>{if(req.body[f]!==undefined) listings[idx].social[f]=req.body[f];}); if(req.body.tags) listings[idx].tags=req.body.tags.split(',').map(t=>t.trim()).filter(Boolean); if(req.files?.images?.length) listings[idx].images=req.files.images.map(f=>`/uploads/images/${f.filename}`); const owner=readJSON(USERS_FILE).find(u=>u.id===req.user.id); if(req.body.customCta!==undefined&&userHasFeature(owner,'custom_cta')) listings[idx].ctaConfig=req.body.customCta?{url:req.body.customCta,label:req.body.ctaLabel||'Contact Now'}:null; if(req.body.sponsored!==undefined&&userHasFeature(owner,'sponsored_listing')) listings[idx].sponsored=req.body.sponsored==='true'; listings[idx].updatedAt=new Date().toISOString(); writeJSON(LISTINGS_FILE,listings); res.json({success:true,listing:listings[idx]}); });

app.delete('/api/listings/:id', authMiddleware, (req,res)=>{ const listings=readJSON(LISTINGS_FILE); const listing=listings.find(l=>l.id===req.params.id); if(!listing) return res.status(404).json({error:'Not found'}); if(listing.ownerId!==req.user.id) return res.status(403).json({error:'Forbidden'}); writeJSON(LISTINGS_FILE,listings.filter(l=>l.id!==req.params.id)); res.json({success:true}); });

app.post('/api/listings/:id/save', authMiddleware, (req,res)=>{ const users=readJSON(USERS_FILE); const idx=users.findIndex(u=>u.id===req.user.id); if(idx===-1) return res.status(404).json({error:'User not found'}); const saved=users[idx].saved||[]; const already=saved.includes(req.params.id); users[idx].saved=already?saved.filter(id=>id!==req.params.id):[...saved,req.params.id]; writeJSON(USERS_FILE,users); const listings=readJSON(LISTINGS_FILE); const lidx=listings.findIndex(l=>l.id===req.params.id); if(lidx!==-1){listings[lidx].saves=(listings[lidx].saves||0)+(already?-1:1);writeJSON(LISTINGS_FILE,listings);} res.json({success:true,saved:!already}); });

app.get('/api/listings/:id/analytics', authMiddleware, (req,res)=>{ const listings=readJSON(LISTINGS_FILE); const listing=listings.find(l=>l.id===req.params.id); if(!listing) return res.status(404).json({error:'Not found'}); if(listing.ownerId!==req.user.id) return res.status(403).json({error:'Forbidden'}); res.json({views:listing.views||0,leads:listing.leads||0,saves:listing.saves||0,rating:listing.rating||0,reviewCount:listing.reviewCount||0,history:listing.analyticsHistory||[]}); });

// REVIEWS
app.post('/api/listings/:id/reviews', authMiddleware, (req,res)=>{ const {rating,comment}=req.body; if(!rating||!comment) return res.status(400).json({error:'rating and comment required.'}); const reviews=readJSON(REVIEWS_FILE); if(reviews.find(r=>r.listingId===req.params.id&&r.userId===req.user.id)) return res.status(400).json({error:'You already reviewed this listing.'}); const review={id:uuidv4(),listingId:req.params.id,userId:req.user.id,userName:req.user.name,rating:Number(rating),comment:comment.trim(),createdAt:new Date().toISOString()}; reviews.push(review); writeJSON(REVIEWS_FILE,reviews); const lr=reviews.filter(r=>r.listingId===req.params.id); const avg=lr.reduce((a,r)=>a+r.rating,0)/lr.length; const listings=readJSON(LISTINGS_FILE); const idx=listings.findIndex(l=>l.id===req.params.id); if(idx!==-1){listings[idx].rating=Math.round(avg*10)/10;listings[idx].reviewCount=lr.length;writeJSON(LISTINGS_FILE,listings);} res.json({success:true,review}); });
app.get('/api/listings/:id/reviews', (req,res)=>res.json(readJSON(REVIEWS_FILE).filter(r=>r.listingId===req.params.id)));

// MESSAGES
app.post('/api/listings/:id/contact', (req,res)=>{ try{ const {senderName,senderEmail,senderPhone,message}=req.body; if(!senderName||!senderEmail||!message) return res.status(400).json({error:'name, email and message required.'}); const listings=readJSON(LISTINGS_FILE); const listing=listings.find(l=>l.id===req.params.id); if(!listing) return res.status(404).json({error:'Listing not found'}); const messages=readJSON(MESSAGES_FILE); messages.push({id:uuidv4(),listingId:req.params.id,businessName:listing.businessName,senderName,senderEmail,senderPhone:senderPhone||null,message,createdAt:new Date().toISOString(),read:false}); writeJSON(MESSAGES_FILE,messages); const idx=listings.findIndex(l=>l.id===req.params.id); if(idx!==-1){listings[idx].leads=(listings[idx].leads||0)+1;const today=new Date().toISOString().slice(0,10);if(!listings[idx].analyticsHistory)listings[idx].analyticsHistory=[];const e=listings[idx].analyticsHistory.find(e=>e.date===today);if(e)e.leads=(e.leads||0)+1;else listings[idx].analyticsHistory.push({date:today,views:0,leads:1});writeJSON(LISTINGS_FILE,listings);} res.json({success:true,message:'Message sent to business owner.'}); }catch(err){console.error(err);res.status(500).json({error:'Server error.'});} });
app.get('/api/messages', authMiddleware, (req,res)=>{ const ids=readJSON(LISTINGS_FILE).filter(l=>l.ownerId===req.user.id).map(l=>l.id); res.json(readJSON(MESSAGES_FILE).filter(m=>ids.includes(m.listingId))); });
app.put('/api/messages/:id/read', authMiddleware, (req,res)=>{ const messages=readJSON(MESSAGES_FILE); const idx=messages.findIndex(m=>m.id===req.params.id); if(idx===-1) return res.status(404).json({error:'Not found'}); messages[idx].read=true; writeJSON(MESSAGES_FILE,messages); res.json({success:true}); });

// FEATURE 1: INVITE & COMMUNITY (Business Pro)
app.post('/api/listings/:id/invite', authMiddleware, (req,res)=>{ const listing=readJSON(LISTINGS_FILE).find(l=>l.id===req.params.id); if(!listing) return res.status(404).json({error:'Not found'}); if(listing.ownerId!==req.user.id) return res.status(403).json({error:'Forbidden'}); const owner=readJSON(USERS_FILE).find(u=>u.id===req.user.id); if(!userHasFeature(owner,'invite_customers')) return res.status(403).json({error:'Upgrade to Business Pro to invite customers.',upgradeRequired:true}); const invites=readJSON(INVITES_FILE); let invite=invites.find(i=>i.listingId===req.params.id); if(!invite){invite={id:uuidv4(),listingId:req.params.id,code:uuidv4().replace(/-/g,'').slice(0,10),createdAt:new Date().toISOString(),uses:0};invites.push(invite);writeJSON(INVITES_FILE,invites);} res.json({success:true,invite,inviteUrl:`/join/${invite.code}`}); });

app.post('/api/invite/:code', optionalAuth, (req,res)=>{ const invites=readJSON(INVITES_FILE); const invite=invites.find(i=>i.code===req.params.code); if(!invite) return res.status(404).json({error:'Invite not found or expired.'}); const listing=readJSON(LISTINGS_FILE).find(l=>l.id===invite.listingId); if(!listing) return res.status(404).json({error:'Business not found.'}); const idx=invites.findIndex(i=>i.code===req.params.code); invites[idx].uses=(invites[idx].uses||0)+1; writeJSON(INVITES_FILE,invites); let followed=false; if(req.user){const follows=readJSON(FOLLOWS_FILE);if(!follows.find(f=>f.userId===req.user.id&&f.listingId===invite.listingId)){follows.push({id:uuidv4(),userId:req.user.id,listingId:invite.listingId,followedAt:new Date().toISOString()});writeJSON(FOLLOWS_FILE,follows);followed=true;}} res.json({success:true,listing:{id:listing.id,businessName:listing.businessName,category:listing.category},followed}); });

app.post('/api/listings/:id/follow', authMiddleware, (req,res)=>{ const follows=readJSON(FOLLOWS_FILE); const already=follows.find(f=>f.userId===req.user.id&&f.listingId===req.params.id); if(already){writeJSON(FOLLOWS_FILE,follows.filter(f=>!(f.userId===req.user.id&&f.listingId===req.params.id)));return res.json({success:true,following:false});} follows.push({id:uuidv4(),userId:req.user.id,listingId:req.params.id,followedAt:new Date().toISOString()});writeJSON(FOLLOWS_FILE,follows);res.json({success:true,following:true}); });

app.get('/api/listings/:id/followers', authMiddleware, (req,res)=>{ const listing=readJSON(LISTINGS_FILE).find(l=>l.id===req.params.id); if(!listing) return res.status(404).json({error:'Not found'}); if(listing.ownerId!==req.user.id) return res.status(403).json({error:'Forbidden'}); const follows=readJSON(FOLLOWS_FILE).filter(f=>f.listingId===req.params.id); const users=readJSON(USERS_FILE); const followers=follows.map(f=>{const u=users.find(u=>u.id===f.userId);if(!u)return null;const {password:_,...safe}=u;return {...safe,followedAt:f.followedAt};}).filter(Boolean); res.json({total:followers.length,followers}); });

app.get('/api/following', authMiddleware, (req,res)=>{ const follows=readJSON(FOLLOWS_FILE).filter(f=>f.userId===req.user.id); const listings=readJSON(LISTINGS_FILE); res.json(follows.map(f=>listings.find(l=>l.id===f.listingId)).filter(Boolean)); });

app.post('/api/listings/:id/broadcast', authMiddleware, (req,res)=>{ const {title,message}=req.body; if(!title||!message) return res.status(400).json({error:'title and message required.'}); const listing=readJSON(LISTINGS_FILE).find(l=>l.id===req.params.id); if(!listing) return res.status(404).json({error:'Not found'}); if(listing.ownerId!==req.user.id) return res.status(403).json({error:'Forbidden'}); const owner=readJSON(USERS_FILE).find(u=>u.id===req.user.id); if(!userHasFeature(owner,'broadcasts')) return res.status(403).json({error:'Upgrade to Business Pro to send broadcasts.',upgradeRequired:true}); const broadcasts=readJSON(BROADCASTS_FILE); const broadcast={id:uuidv4(),listingId:req.params.id,businessName:listing.businessName,title:title.trim(),message:message.trim(),createdAt:new Date().toISOString()}; broadcasts.unshift(broadcast); writeJSON(BROADCASTS_FILE,broadcasts); res.json({success:true,broadcast}); });

app.get('/api/feed', authMiddleware, (req,res)=>{ const follows=readJSON(FOLLOWS_FILE).filter(f=>f.userId===req.user.id); const ids=follows.map(f=>f.listingId); const broadcasts=readJSON(BROADCASTS_FILE).filter(b=>ids.includes(b.listingId)); broadcasts.sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)); res.json(broadcasts.slice(0,50)); });

app.get('/api/listings/:id/broadcasts', (req,res)=>res.json(readJSON(BROADCASTS_FILE).filter(b=>b.listingId===req.params.id).slice(0,20)));

app.post('/api/listings/:id/stamp', authMiddleware, (req,res)=>{ const listing=readJSON(LISTINGS_FILE).find(l=>l.id===req.params.id); if(!listing) return res.status(404).json({error:'Not found'}); const owner=readJSON(USERS_FILE).find(u=>u.id===listing.ownerId); if(!userHasFeature(owner,'loyalty_stamps')) return res.status(403).json({error:'This business does not have stamps enabled.'}); const stamps=readJSON(STAMPS_FILE); let card=stamps.find(s=>s.userId===req.user.id&&s.listingId===req.params.id); if(!card){card={id:uuidv4(),userId:req.user.id,listingId:req.params.id,stamps:0,redeemed:0,lastStamp:null};stamps.push(card);} card.stamps++;card.lastStamp=new Date().toISOString();writeJSON(STAMPS_FILE,stamps);res.json({success:true,stamps:card.stamps,redeemed:card.redeemed}); });
app.get('/api/listings/:id/my-stamps', authMiddleware, (req,res)=>{ const card=readJSON(STAMPS_FILE).find(s=>s.userId===req.user.id&&s.listingId===req.params.id); res.json(card||{stamps:0,redeemed:0}); });

// FEATURE 2: GROWTH SUITE
app.get('/api/listings/:id/leads/export', authMiddleware, (req,res)=>{ const listing=readJSON(LISTINGS_FILE).find(l=>l.id===req.params.id); if(!listing) return res.status(404).json({error:'Not found'}); if(listing.ownerId!==req.user.id) return res.status(403).json({error:'Forbidden'}); const owner=readJSON(USERS_FILE).find(u=>u.id===req.user.id); if(!userHasFeature(owner,'lead_export')) return res.status(403).json({error:'Upgrade to Growth Suite to export leads.',upgradeRequired:true}); const messages=readJSON(MESSAGES_FILE).filter(m=>m.listingId===req.params.id); const rows=[['Date','Name','Email','Phone','Message'],...messages.map(m=>[m.createdAt,m.senderName,m.senderEmail,m.senderPhone||'',m.message.replace(/,/g,' ')])]; const csv=rows.map(r=>r.map(c=>`"${c}"`).join(',')).join('\n'); res.setHeader('Content-Type','text/csv'); res.setHeader('Content-Disposition',`attachment; filename="leads-${req.params.id}.csv"`); res.send(csv); });

app.get('/api/listings/:id/competitor-analytics', authMiddleware, (req,res)=>{ const listing=readJSON(LISTINGS_FILE).find(l=>l.id===req.params.id); if(!listing) return res.status(404).json({error:'Not found'}); if(listing.ownerId!==req.user.id) return res.status(403).json({error:'Forbidden'}); const owner=readJSON(USERS_FILE).find(u=>u.id===req.user.id); if(!userHasFeature(owner,'competitor_analytics')) return res.status(403).json({error:'Upgrade to Growth Suite for competitor analytics.',upgradeRequired:true}); const peers=readJSON(LISTINGS_FILE).filter(l=>l.status==='active'&&l.category===listing.category&&l.id!==listing.id).map(l=>({id:l.id,businessName:l.businessName,views:l.views||0,leads:l.leads||0,saves:l.saves||0,rating:l.rating||0,reviewCount:l.reviewCount||0})); const avgViews=peers.length?Math.round(peers.reduce((a,p)=>a+p.views,0)/peers.length):0; const avgLeads=peers.length?Math.round(peers.reduce((a,p)=>a+p.leads,0)/peers.length):0; const avgRating=peers.length?(peers.reduce((a,p)=>a+p.rating,0)/peers.length).toFixed(1):0; res.json({yourStats:{views:listing.views||0,leads:listing.leads||0,saves:listing.saves||0,rating:listing.rating||0},categoryAverages:{views:avgViews,leads:avgLeads,rating:Number(avgRating)},totalCompetitors:peers.length,topCompetitors:peers.sort((a,b)=>b.views-a.views).slice(0,5)}); });

// USERS / STATS / CATEGORIES
app.get('/api/users/:id', (req,res)=>{ const user=readJSON(USERS_FILE).find(u=>u.id===req.params.id); if(!user) return res.status(404).json({error:'Not found'}); const {password:_,...safe}=user; res.json(safe); });
app.get('/api/stats', (req,res)=>{ const listings=readJSON(LISTINGS_FILE).filter(l=>l.status==='active'); const users=readJSON(USERS_FILE); res.json({activeListings:listings.length,totalUsers:users.length,categories:[...new Set(listings.map(l=>l.category))].length,countries:[...new Set(listings.map(l=>l.country).filter(Boolean))].length}); });
app.get('/api/categories', (req,res)=>{ const counts={}; readJSON(LISTINGS_FILE).filter(l=>l.status==='active').forEach(l=>{counts[l.category]=(counts[l.category]||0)+1;}); res.json(counts); });

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`GrowthMarket v3 running on port ${PORT}`));
